#!/bin/bash -l       
#PBS -P rj76 
#PBS -l walltime=1:00:00,ncpus=4,mem=16G
#PBS -M ewilkie@ccia.org.au
#PBS -l storage=gdata/rj76+gdata/tx70
#PBS -q express
#PBS -M ewilkie@ccia.org.au
#PBS -m abe

module load bcftools/1.9
module load htslib/1.9 

FILES=/g/data/tx70/private/ew8662/Software/nimpress/preprocess/Output/NIMPRESS/*

for file in $FILES
do
    echo "$file" 
    basename="${file##*/}"
    basename2="${basename%_*}"
    echo "$basename"
    echo "$basename2"
    nimpress "$file" /g/data3/tx70/results/landscape_paper/germline_joint_call/results/02_genotype_gvcfs/landscape.germline_hc.merged.bcf > /g/data/tx70/private/ew8662/Software/nimpress/scores/"$basename2"_nimpress_res.txt
done


